In [1]:
from scipy.stats import chi2_contingency
import numpy as np

In [2]:
table = np.array([[90, 60, 104, 95], [30, 50, 51, 20], [30, 40, 45, 35]])

In [3]:
chisquared_value, p_value, dof, expected = chi2_contingency(table) 

In [4]:
print('Chi-Squared value: %.1f' % chisquared_value)

Chi-Squared value: 24.6


In [5]:
print('p value: %.10f' % p_value)

p value: 0.0004098426


In [6]:
print('Degrees of freedom: %.1f' % dof)

Degrees of freedom: 6.0


In [7]:
print(expected)

[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]
